#!/bin/sh

set -e

if [ $# -eq 0 ]; then
  echo "no dockerfile supplied"
  exit 1
fi

NAME=${1%.*}
DOCKERFILE="$NAME.dockerfile"
TOOLS=machine-emulator-tools-v0.12.0.tar.gz

if [ ! -f "$DOCKERFILE" ]; then
  echo "dockerfile \"$DOCKERFILE\" not found"
  exit 1
fi

if [ ! -f "$TOOLS" ]; then
  echo "tools tarball \"$TOOLS\" not found"
  exit 1
fi

TAR=$(mktemp) && \
docker buildx build --progress plain \
  --build-arg TOOLS=$TOOLS \
  --output type=tar,dest=$TAR \
  --file $NAME.dockerfile \
  . && \
GNUTAR=$(mktemp) && \
bsdtar -cf $GNUTAR --format=gnutar @$TAR
./img-pack $GNUTAR $NAME.ext2 rootfs && (rm -f $TAR $GNUTAR; echo "created $NAME.ext2"; true) || (rm -f $TAR $GNUTAR; false)
