#!/bin/sh
blocksize=4096
bytes=$(($(wc -c < "$1") +0))
bcargs="$(cat <<- EOF
	define max(a, b) { return (a > b) * a + (a <= b) * b }
	max(8, 1.2 * ($bytes + $blocksize - 1) / $blocksize)
	EOF
)"
blocks=$(echo "$bcargs" | bc)

genext2fs \
	-fzB $blocksize \
	-b   $blocks \
	-i   $blocksize \
	-L   ${3:-rootfs} \
	-a   $1 \
	$2
