#!/bin/sh
# Copyright 2022 Cartesi Pte. Ltd.
#
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

DEFAULT_ROLLUP_HTTP_SERVER_TIMEOUT=100
DEFAULT_ROLLUP_HTTP_SERVER_PORT=5004

usage() {
    echo "Usage:

    $0 [options] <command> [arguments]

where options are:

    --help
        Prints this message.

    --rollup-http-server-port <port>
        Passes to the rollup-http-server the port it should listen to.
        (default: $DEFAULT_ROLLUP_HTTP_SERVER_PORT)

    --rollup-http-server-timeout <seconds>
        Maximum number of seconds that the dapp should take to start up.
        (default: $DEFAULT_ROLLUP_HTTP_SERVER_TIMEOUT)

    --rollup-http-server-verbose
        Enables verbose messages from the rollup-http-server.
        (default: disabled)

and command and arguments:

    command
        The command to start up the dapp.

    arguments
        The given command arguments."
}

check_integer() {
    if [ $# -eq 0 ]
    then
        echo "Error: missing argument" >&2
        exit 1
    fi
    if ! [ $1 -eq $1 ] > /dev/null 2>&1
    then
        echo "Error: port must be a number" >&2
        exit 1
    fi
}

ROLLUP_HTTP_SERVER_TIMEOUT=$DEFAULT_ROLLUP_HTTP_SERVER_TIMEOUT
ROLLUP_HTTP_SERVER_PORT=$DEFAULT_ROLLUP_HTTP_SERVER_PORT
ROLLUP_HTTP_SERVER_VERBOSE=""

while [ $# -gt 0 ]
do
    case "$1" in
    --help)
        usage
        exit 0
        ;;
    --rollup-http-server-port)
        shift
        check_integer $1
        ROLLUP_HTTP_SERVER_PORT=$1
        shift
        ;;
    --rollup-http-server-timeout)
        shift
        check_integer $1
        ROLLUP_HTTP_SERVER_TIMEOUT=$1
        shift
        ;;
    --rollup-http-server-verbose)
        ROLLUP_HTTP_SERVER_VERBOSE="--verbose"
        shift
        ;;
    -*)
        echo "Error: unknown option $1" >&2
        exit 1
        ;;
    *)
        break
        ;;
    esac
done

# Start http dispatcher
echo "Starting rollup-http-server: "
sh -c "rollup-http-server \
    --address 127.0.0.1:$ROLLUP_HTTP_SERVER_PORT \
    $ROLLUP_HTTP_SERVER_VERBOSE" &

# Wait for the rollup http server to start up
RETRY=0
while ! netstat -ntl 2>&1 | grep $ROLLUP_HTTP_SERVER_PORT > /dev/null
do
    echo -n "."
    sleep 1
    RETRY=$((RETRY + 1))
    if [ $RETRY -ge $ROLLUP_HTTP_SERVER_TIMEOUT ]
    then
        echo "Error: rollup http server timed out"
        exit 1
    fi
done
echo "Rollup http server started"
echo ""


# Check if there are any arguments left to start up the dapp
if [ $# -eq 0 ]
then
    echo "Error: missing dapp startup command" >&2
    exit 1
fi

# Start dapp
echo -n "Starting dapp: " "$*"
sh -c "$*"

echo "Result:" $?
